### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [gvin10/Splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by gvin10** [comment]
So it seems adding the viewport meta tag:
<meta name="viewport" content="width=device-width, initial-scale=1">

Will resize for mobile though I'm not sure where to place it. I put it at the top of the application.html.erb file though that didn't change anything.
![capture](https://user-images.githubusercontent.com/32856525/31920512-6860653a-b81e-11e7-8fe1-e0d35a41b993.JPG)

**Comment by Mikeysax** [comment]
Google is your best friend when learning and dealing with development related tasks. Try searching for mobile meta tag in google. Hint: Some people call it something else.

**Comment by gvin10** [comment]
@Mikeysax I finally fixed it, https://github.com/gvin10/Splurty/commit/e74dfd1d2cb983df0d46c8da28bd94c021853d6b

**Comment by Mikeysax** [comment]
Good job, very close. You'll need to place the meta tag in the `head` of the application layout file. You don't need it in multiple places.

**Comment by gvin10** [comment]
Ok I moved it in the head.

All the best,
Gregorio

**Comment by Mikeysax** [comment]
:+1:
